Modified the Workflow to abort when there is a conflict in a file different form the Model.

diff --git a/.github/workflows/RebasePrByComments.yml b/.github/workflows/RebasePrByComments.yml
--- a/.github/workflows/RebasePrByComments.yml
+++ b/.github/workflows/RebasePrByComments.yml
@@ -88,17 +88,24 @@ jobs:
           $lta = '${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}'
           $gitcmd = 'C:\Program Files\Git\git-cmd.exe'
           
-          echo "set user config"
+          Write-Output "set user config"
           git config --global user.name 'LemonTree.Automation'
           git config --global user.email 'support@lieberlieber.com'
 
-          echo "setting remote state"
+          Write-Output "setting remote state"
           git remote set-url origin https://x-access-token:${{secrets.PAT}}@github.com/${{ github.repository }}
           git status --porcelain --untracked-files=no --ignored=no
           
           git rebase origin/main
           
           while($LASTEXITCODE -ne 0) {
+              $status = git status -s
+              if($status -ne "UU ${{env.ModelName}}.${{env.ModelExtension}}") {
+                Write-Output "::error::Model is not conflicted please rebase manually."
+                echo "message=:x: Failed to rebase, the Model is not the only conflict." >> $env:GITHUB_OUTPUT
+                exit 666
+              }
+          
               $basecommit = git merge-base HEAD REBASE_HEAD
               $command = 'git cat-file blob {0}:${{env.ModelName}}.${{env.ModelExtension}} | git lfs smudge > ${{env.ModelName}}_base.${{env.ModelExtension}} & exit' -f $basecommit
               #this is required to get rid of the line feeds in the basecommit string
@@ -109,26 +116,26 @@ jobs:
               &$lta merge --Base ${{env.ModelName}}_base.${{env.ModelExtension}} --Theirs ${{env.ModelName}}_theirs.${{env.ModelExtension}} --Mine ${{env.ModelName}}_mine.${{env.ModelExtension}} --out ${{env.ModelName}}.${{env.ModelExtension}}
           
               if($LASTEXITCODE -eq 0){
-                echo "No merge conflicts, setting message"
+                Write-Output "No merge conflicts, setting message"
                 echo "message=:heavy_check_mark: Rebase performed successfully" >> $env:GITHUB_OUTPUT
               }
               elseif($LASTEXITCODE -eq 2){
-                echo "::error::Internal Error when diffing. Please report such errors to support@lieberlieber.com"
+                Write-Output "::error::Internal Error when diffing. Please report such errors to support@lieberlieber.com"
                 echo "message=x: Rebase failed, check [action log](${{env.GitHubProjectRoot}}/actions/runs/${{ github.run_id }}) for details" >> $env:GITHUB_OUTPUT
                 exit 2
               }
               elseif($LASTEXITCODE -eq 3){
-                echo "Merge conflicts present, auto-merge failed"
+                Write-Output "Merge conflicts present, auto-merge failed"
                 echo "message=:x: Merge conflicts present, auto-rebase failed" >> $env:GITHUB_OUTPUT
                 exit 3
               }
               elseif($LASTEXITCODE -eq 6){
-                echo "::warning::Licensing issue of LemonTree.Automation"
+                Write-Output "::warning::Licensing issue of LemonTree.Automation"
                 echo "message=:x: Rebase failed, check [action log](${{env.GitHubProjectRoot}}/actions/runs/${{ github.run_id }}) for details" >> $env:GITHUB_OUTPUT
                 exit 6
               }
               else{
-                echo "::error::Unknown error"
+                Write-Output "::error::Unknown error"
                 echo "message=x: Rebase failed, check [action log](${{env.GitHubProjectRoot}}/actions/runs/${{ github.run_id }}) for details" >> $env:GITHUB_OUTPUT
                 exit 1
               }
